name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - "components/**/*"
      - "tools/**/*"

permissions:
  contents: read
  pull-requests: write

jobs:
  vrt:
    name: Visual regression testing
    # Run VRT only if the PR is not a draft and has the label 'run_vrt' and does not have the label 'skip_vrt'
    if: github.event.pull_request.draft != true || (github.event.pull_request.draft == true && contains(github.event.pull_request.labels.*.name, 'run_vrt'))

    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: ci:storybook
          storybookConfigDir: tools/preview
          exitOnceUploaded: true
          onlyChanged: true
          traceChanged: true
          diagnostics: true
          # this lets the VRT pass without running it if the PR has the label 'skip_vrt'
          skip: ${{ contains(github.event.pull_request.labels.*.name, 'skip_vrt') }}
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: chromatic-build-artifacts-${{ github.run_id }}
          path: |
            **/chromatic-diagnostics.json
            **/build-storybook.log

  build_base:
    name: Build the base branch
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.pull_request.base.ref }}
      path: ${{ github.event.pull_request.base.ref }}
      sha: ${{ github.event.pull_request.base.sha }}
    secrets: inherit

  build_pr:
    name: Build this pull request
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      path: ${{ github.event.pull_request.base.ref }}
      sha: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  compare_results:
    name: Compare compiled output
    runs-on: ubuntu-latest
    needs: [build_base, build_pr]
    steps:
      - name: Download the artifacts for this PR
        uses: actions/download-artifact@v3
        with:
          name: compiled-${{ github.event.pull_request.head.sha }}
          path: pull-request
      - name: Download the artifacts for the base branch
        uses: actions/download-artifact@v3
        with:
          name: compiled-${{ github.event.pull_request.base.sha }}
          path: base-branch
      - uses: pr-comment-file-size@v3.1.1
        with:
          path: ${{ github.workspace }}/pull-request
          diff_path: ${{ github.workspace }}/base-branch
          file_glob_pattern: |
            "components/*/dist/*.css"
            "components/*/dist/themes/*.css"
